Sending email on failure

diff --git a/.github/workflows/upload_baseline_and_ensemble.yml b/.github/workflows/upload_baseline_and_ensemble.yml
--- a/.github/workflows/upload_baseline_and_ensemble.yml
+++ b/.github/workflows/upload_baseline_and_ensemble.yml
@@ -95,9 +95,10 @@ jobs:
       # ERROR RUN
       # --------------------------------------------
       - name: Error
-        if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
+        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'error'}}
         run: |
           echo "EnsambleUPLOAD FAILED -  ignore djson db cleaning"
+          exit 1
 
       # Final commit
       # --------------------------------------------
@@ -109,3 +110,24 @@ jobs:
           message: "Update model-output db json"
           default_author: github_actions
           push: true
+
+      # FAILURE NOTIFICATION
+      # --------------------------------------------
+      - name: Send warning email to admin
+        if: ${{ failure() }}
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.EMAIL_USERNAME }}
+          password: ${{ secrets.EMAIL_PASSWORD }}
+          subject: "Influcast - Baseline and Ensemble upload error!"
+          body: |
+            Hi,
+
+            An error occurred during the Baseline and Ensemble Upload workflow.
+
+            InfluCast tech team.
+          to: paolo.milano@isi.it,corrado.gioannini@isi.it,nicolo.gozzi@isi.it
+          from: "Influcast Team <influcast@isi.it>"
+          content_type: text/plain
